use_frameworks!

platform :ios, '10.0'

target 'tt_abc_Example' do
  pod 'tt_abc', :path => '../'

  target 'tt_abc_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
